// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// O pooler do Neon (-pooler) usa PgBouncer em Transaction mode, que não suporta advisory locks.
// Remover '-pooler' conecta diretamente ao Postgres para o prisma migrate deploy.
const rawUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "";
const migrationUrl = rawUrl.replace("-pooler.", ".");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || (migrationUrl.includes("localhost") || migrationUrl.includes("127.0.0.1") ? "postgresql://postgres:postgres@localhost:5432/rm_frotas_shadow?schema=public" : undefined),
  },
});
