export enum SuspensionReasonCategory {
  CNH_VENCIDA = 'CNH_VENCIDA',
  ACIDENTE = 'ACIDENTE',
  PROCESSO_DISCIPLINAR = 'PROCESSO_DISCIPLINAR',
  EXAME_TOXICOLOGICO_PENDENTE = 'EXAME_TOXICOLOGICO_PENDENTE',
  DOCUMENTACAO_IRREGULAR = 'DOCUMENTACAO_IRREGULAR',
  OUTRO = 'OUTRO',
}
